spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.76.203.218:3306/test
    username: root
    password: 123456
  session:
    timeout: 86400 # 设置超时时间为一天

server:
  address: 0.0.0.0
